### ISSUE TITLE
upgraded project to capacitor 4, ionic/xcode project will not compile

### ISSUE THREAD

**Issue by Nathan187** [BranchMetrics/capacitor-branch-deep-links#65]
<img width="1152" alt="Screen Shot 2022-09-16 at 7 51 11 AM" src="https://user-images.githubusercontent.com/1022238/190643053-c4064139-ff44-441f-80ea-c0922e82e71e.png">
### Describe the bug

getting the following errors:  

Cannot find type 'BranchQRCode' in scope

Cannot convert value of type '_' to expected argument type 'Stri

both occurring in the branchserice.swift file (of the framework)

### Steps to reproduce

1. create an ionic project that uses capacitor 4
2.use the component branch deep links 5.0
3.

### Expected behavior

expect the project to compile and run

### SDK Version

5.0

### Make and Model

iphone

### OS

13

### Additional Information/Context

nothing more to add

**Comment by dtarnawsky** [comment]
This can be fixed by opening your app's Podfile and making sure that under the line: `post_install do |installer|` it has the following line:
`assertDeploymentTarget(installer)`

This ensures that the podspec files for any plugins will target iOS 13.0 and allows plugins to work in projects that use iOS 12.0 to work.

The branch plugin in v5.0.0 is only targeting iOS 13.0 so I've created a pull request to resolve that.

**Comment by Nathan187** [comment]
for some reason, the banch pod was out of date.  updating it fixed the issues (and deleting derived data folder)
